apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-configmap
data:
  REACT_APP_MATRIX_URL: "https://{{ .Values.global.domains.matrix }}"
  REACT_APP_KEYCLOAK_URL: "https://{{ .Values.global.domains.auth }}"
  VITE_API_URL: "https://{{ .Values.global.domainName }}"