apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
data:
  allow-snippet-annotations: "true"
  annotations-risk-level: "Critical"
