apiVersion: v1
kind: ConfigMap
metadata:
  name: element-call-config
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
    {
      "default_server_config": {
        "m.homeserver": {
          "base_url": "{{ if .Values.global.enableTls }}https{{ else }}http{{ end }}://{{ .Values.global.domainName }}",
          "server_name": "{{ .Values.matrix.matrixServerName }}"
        }
      },
      "livekit": {
        "livekit_service_url": "{{ if .Values.global.enableTls }}https{{ else }}http{{ end }}://{{ .Values.global.domainName }}/livekit/jwt"
      },
      "features": {
        "feature_use_device_session_member_events": true
      },
      "ssla": "https://static.element.io/legal/element-software-and-services-license-agreement-uk-1.pdf",
      "matrix_rtc_session": {
        "wait_for_key_rotation_ms": 3000,
        "membership_event_expiry_ms": 180000000,
        "delayed_leave_event_delay_ms": 18000,
        "delayed_leave_event_restart_ms": 4000,
        "network_error_retry_ms": 100
      }
    }
