apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tenantservice.fullname" . }}-secrets
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    {{- include "tenantservice.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Database Credentials
  SPRING_DATASOURCE_USERNAME: {{ .Values.database.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.database.password | quote }}
  SPRING_RABBITMQ_USERNAME:   {{ .Values.rabbitmq.username | quote }}
  SPRING_RABBITMQ_PASSWORD:   {{ .Values.rabbitmq.password | quote }}


