apiVersion: v1
kind: Service
metadata:
  name: livekit-token-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3010
      targetPort: 3010
  selector:
    app: livekit-token-service
  type: ClusterIP