apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agencyservice.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    {{- include "agencyservice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "agencyservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "agencyservice.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: agencyservice
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ include "agencyservice.fullname" . }}-config
        - secretRef:
            name: {{ include "agencyservice.fullname" . }}-secrets
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
        {{- if .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        {{- end }}
