apiVersion: v1
kind: Service
metadata:
  name: livekit
  namespace: {{ .Release.Namespace }}
  labels:
    app: livekit
spec:
  type: ClusterIP
  selector:
    app: livekit
  ports:
    - name: http
      port: 7880
      targetPort: 7880
      protocol: TCP
