apiVersion: v1
kind: Service
metadata:
  name: livekit-token-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.tokenService.service.type }}
  ports:
  - port: {{ .Values.tokenService.service.port }}
    targetPort: {{ .Values.tokenService.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: livekit-token-service